#!/bin/bash

SCRIPTPATH=`dirname $(readlink -f $0)`
IMGNAME=`basename $SCRIPTPATH`.b1

cd $SCRIPTPATH

# build the image
sudo docker build -t $IMGNAME .
sudo docker run -it --rm --name running-$IMGNAME $IMGNAME $1
